name: peninsulabalvihar
description: An app containing the Peninsula Balavihar prayers, shlokams, & songs.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  get: any
  flutter_neumorphic: ^2.2.2
  google_fonts: ^1.1.0
  just_audio: ^0.1.10
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

