name: peninsulabalvihar
description: An app containing the Peninsula Balvihar prayers, shlokams, & songs.

version: 1.0.0+2

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter_hooks: ^0.16.0
  hooks_riverpod: ^0.13.1
  fluro: ^2.0.3
  google_fonts: ^2.0.0
  just_audio: ^0.7.0
  animate_do: ^2.0.0
  flutter_fluid_slider: ^1.0.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: any
  pedantic: any
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/BVLogo.jpg"

flutter:
  uses-material-design: true

