name: peninsulabalvihar
description: An app containing the Peninsula Balvihar prayers, shlokams, & songs.

version: 0.1.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  get: ^2.7.1
  flutter_neumorphic: ^2.2.0
  google_fonts: ^1.1.0
  just_audio: ^0.4.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  seekbar: ^0.0.2

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/BVLogo.png"

flutter:
  uses-material-design: true

