name: peninsulabalvihar
description: An app containing the Peninsula Balvihar prayers, shlokams, & songs.

version: 1.0.0+2

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter_hooks: any
  hooks_riverpod: any
  beamer: any
  flutter_neumorphic: ^2.2.0
  google_fonts: ^1.1.0
  just_audio: ^0.6.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: any
  pedantic: any
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/BVLogo.jpg"

flutter:
  uses-material-design: true

